name: JOTTA Twitch Clip Watcher

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-clips:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check JOTTA clips
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_CHANNEL: jotta

          DISCORD_CLIP_WEBHOOK_URL: ${{ secrets.DISCORD_CLIP_WEBHOOK_URL }}
          DISCORD_STATUS_WEBHOOK_URL: ${{ secrets.DISCORD_STATUS_WEBHOOK_URL }}

        run: |
          python src/main.py

      - name: Save clip database
        if: always()
        run: |
          if git diff --quiet -- data/seen_clips.json; then
            echo "No database changes."
            exit 0
          fi

          git config user.name "JOTTA Clip Watcher"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/seen_clips.json
          git commit -m "Update seen clips"
          git push
